# Generated by Django 5.2.6 on 2026-03-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
