# Generated by Django 5.2.6 on 2026-04-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
