# Generated by Django 5.2.6 on 2026-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionservice', '0003_paper_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='exam_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
